#!/usr/bin/env bash
set -ex
echo "=== worker SCRIPT CALLED ==="
ls -la ../data
# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_pipeline.py "$@"
