#!/usr/bin/env bash
set -e
###########################################################################
# provided by Tom C
# https://gist.github.com/tmchartrand/0c46bdec6a4205aa7ce7555fd8f4c3b5
###########################################################################
# install updated version of code-server
VERSION=4.103.2
mkdir -p /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xz
ln -sf /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -
mkdir -p /.vscode/extensions
code-server --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter 
code-server --extensions-dir=/.vscode/extensions --install-extension ms-python.python 
code-server --extensions-dir=/.vscode/extensions --install-extension detachhead.basedpyright
code-server --extensions-dir=/.vscode/extensions --install-extension saoudrizwan.claude-dev
# download and install vscode extension from file
# for extensions not available in the default open-vsx registry
# run from within a workstation or in postinstall
# won't work in postinstall if extensions folder has been moved to inside capsule filesystem!
download_and_install_extension() {
    publisher=$1
    name=$2
    version=$3
    file=/tmp/$publisher.$name.$version.vsix
    curl -fL http://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage \
        --output $file
    code-server --extensions-dir=/.vscode/extensions --install-extension $file
}
download_and_install_extension github copilot	1.364.0
download_and_install_extension github copilot-chat 0.30.3

curl -LsSf https://astral.sh/uv/install.sh | \
    UV_INSTALL_DIR=/usr/local/bin sh
uv pip install --system git+https://github.com/AllenNeuralDynamics/aind-zarr-utils.git
# list of requirements
cat > /tmp/requirements.txt <<'REQ'
dask
dask-image
dask[distributed]
h5py
matplotlib
numpy<2
oauthlib
opencv-python
pandas
pillow
scikit-image
scikit-learn
scipy
seaborn
tifffile
torch
tqdm
umap-learn
zarr
ipykernel
openpyxl
ipympl
statsmodels
antspyx
REQ

uv pip install --no-cache --system -r /tmp/requirements.txt && rm /tmp/requirements.txt
